USE DATABASE MEMBER;
USE SCHEMA PUBLIC;

CREATE SEQUENCE IF NOT EXISTS BOARD_POST_ID_SEQ START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS BOARD_POSTS (
  POST_ID NUMBER(38, 0) NOT NULL DEFAULT BOARD_POST_ID_SEQ.NEXTVAL,
  TITLE VARCHAR(80) NOT NULL,
  CONTENT VARCHAR(3000) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ,
  CONSTRAINT PK_BOARD_POSTS PRIMARY KEY (POST_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_ATTACHMENTS (
  ATTACHMENT_ID NUMBER(38, 0) AUTOINCREMENT START 1 INCREMENT 1,
  POST_ID NUMBER(38, 0) NOT NULL,
  FILE_NAME VARCHAR(500) NOT NULL,
  CONTENT_TYPE VARCHAR(255) NOT NULL,
  FILE_SIZE NUMBER(38, 0) NOT NULL,
  FILE_DATA BINARY(10485760) NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_BOARD_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID),
  CONSTRAINT FK_BOARD_ATTACHMENTS_POST FOREIGN KEY (POST_ID)
    REFERENCES BOARD_POSTS (POST_ID)
);
